#index:
#    path: /
#    controller: App\Controller\DefaultController::index

token_generate:
  path:     /token/generate
  methods:    [POST]
  controller: 'App\Controller\TokenController::generateTokenAction'

token_refresh:
  path:     /token/refresh
  methods:    [PUT]
  controller: 'App\Controller\TokenController::refreshTokenAction'

home:
  path:     /
  methods:    [GET]
  controller: 'App\Controller\HomeController::homeAction'

test:
  path:     /test
  methods:    [POST]
  controller: 'App\Controller\HomeController::testAction'

picture:
  path:     /picture
  methods:    [POST, PUT, GET, DELETE]
  controller: 'App\Controller\PictureController::PictureAction'