version: '3.3'
services:

    nginx:
        image: nginx:1.14.2
        ports:
            - "3001:3001"
            - "3002:3002"
            - "443:443"
        volumes:
            - ./Nginx/core:/etc/nginx/conf.d
            - ./Nginx/www:/var/www/
            - ./Nginx/www2:/var/www2/
            - ./Nginx/Logs:/var/log/nginx/
            - ./Nginx/html:/usr/share/nginx/html/
        links:
            - php
            - s3server
        networks:
            - webappnetwork
    mysql:

        image: mysql:5.7

        ports:
            - "3306:3306"
        environment:

            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=temp
            - MYSQL_USER=temp
            - MYSQL_PASSWORD=temp
        volumes:
            - ./MySQL:/var/lib/mysql
        networks:
            - webappnetwork

    php:
        build: ./PHP
        volumes:
            - ./Nginx/www:/var/www

        links:
            - mysql
            - s3server
        networks:
            - webappnetwork

    nodejs:
        build: ./nodejs
        environment:
           - NODE_ENV=production
        links:
           - nginx
        volumes:
           - ./nodejs:/var/www2
        command: npm start
        ports:
           - 3000:3000
        networks:
            - webappnetwork
            
    s3server:
       image: scality/s3server:latest
       container_name: s3server
       restart: always
       ports:
          - "8000:8000"
       volumes:
          - ./S3/s3data:/usr/src/app/localData
          - ./S3/s3metadata:/usr/src/app/localMetadata
          - "${PWD}/s3.json:/usr/src/app/config.json"
       environment:
          - SCALITY_ACCESS_KEY_ID=111
          - SCALITY_SECRET_ACCESS_KEY=111
          - SSL="FALSE"            
       networks:
          - webappnetwork      
            
networks:
   webappnetwork:
      driver: bridge